"""add service alias question models

Revision ID: 41e7d4e237a3
Revises: 2713a74e968f
Create Date: 2026-09-13 11:03:35.017773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e7d4e237a3'
down_revision: Union[str, Sequence[str], None] = '2713a74e968f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_aliases',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=300), nullable=False),
    sa.Column('normalized', sa.String(length=300), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'normalized', name='uq_service_aliases_service_normalized')
    )
    op.create_index(op.f('ix_service_aliases_normalized'), 'service_aliases', ['normalized'], unique=False)
    op.create_index(op.f('ix_service_aliases_service_id'), 'service_aliases', ['service_id'], unique=False)
    op.create_table('service_questions',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('BOOLEAN', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', name='question_type', native_enum=False), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_questions_service_id'), 'service_questions', ['service_id'], unique=False)
    op.create_table('service_question_options',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['service_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'value', name='uq_sqo_question_value')
    )
    op.create_index(op.f('ix_service_question_options_question_id'), 'service_question_options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_question_options_question_id'), table_name='service_question_options')
    op.drop_table('service_question_options')
    op.drop_index(op.f('ix_service_questions_service_id'), table_name='service_questions')
    op.drop_table('service_questions')
    op.drop_index(op.f('ix_service_aliases_service_id'), table_name='service_aliases')
    op.drop_index(op.f('ix_service_aliases_normalized'), table_name='service_aliases')
    op.drop_table('service_aliases')
    # ### end Alembic commands ###
