"""add governorate sector government_entity models

Revision ID: f6be7f4425d7
Revises: 41e7d4e237a3
Create Date: 2026-09-13 12:05:40.323666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6be7f4425d7'
down_revision: Union[str, Sequence[str], None] = '41e7d4e237a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governorates',
    sa.Column('name_ar', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governorates_code'), 'governorates', ['code'], unique=True)
    op.create_index(op.f('ix_governorates_name_ar'), 'governorates', ['name_ar'], unique=False)
    op.create_index(op.f('ix_governorates_region'), 'governorates', ['region'], unique=False)
    op.create_table('sectors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_parent_id'), 'sectors', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sectors_slug'), 'sectors', ['slug'], unique=True)
    op.create_table('government_entities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.Enum('MINISTRY', 'AUTHORITY', 'AGENCY', 'DIRECTORATE', 'ADMINISTRATION', 'COUNCIL', 'OTHER', name='entity_type', native_enum=False), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('governorate_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['government_entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_entities_entity_type'), 'government_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_government_entities_governorate_id'), 'government_entities', ['governorate_id'], unique=False)
    op.create_index(op.f('ix_government_entities_name'), 'government_entities', ['name'], unique=False)
    op.create_index(op.f('ix_government_entities_parent_id'), 'government_entities', ['parent_id'], unique=False)
    op.create_index(op.f('ix_government_entities_sector_id'), 'government_entities', ['sector_id'], unique=False)
    op.create_index(op.f('ix_government_entities_slug'), 'government_entities', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_government_entities_slug'), table_name='government_entities')
    op.drop_index(op.f('ix_government_entities_sector_id'), table_name='government_entities')
    op.drop_index(op.f('ix_government_entities_parent_id'), table_name='government_entities')
    op.drop_index(op.f('ix_government_entities_name'), table_name='government_entities')
    op.drop_index(op.f('ix_government_entities_governorate_id'), table_name='government_entities')
    op.drop_index(op.f('ix_government_entities_entity_type'), table_name='government_entities')
    op.drop_table('government_entities')
    op.drop_index(op.f('ix_sectors_slug'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_parent_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_governorates_region'), table_name='governorates')
    op.drop_index(op.f('ix_governorates_name_ar'), table_name='governorates')
    op.drop_index(op.f('ix_governorates_code'), table_name='governorates')
    op.drop_table('governorates')
    # ### end Alembic commands ###
