"""add government_office emergency_hotline office_services models

Revision ID: fb634843c7a9
Revises: f6be7f4425d7
Create Date: 2026-09-13 12:21:35.460204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb634843c7a9'
down_revision: Union[str, Sequence[str], None] = 'f6be7f4425d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_hotlines',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('hotline_type', sa.Enum('POLICE', 'AMBULANCE', 'FIRE', 'GAS', 'WATER', 'ELECTRICITY', 'SEWAGE', 'CONSUMER', 'HEALTH', 'COMPLAINTS', 'ROADS', 'OTHER', name='hotline_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('governorate_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_national', sa.Boolean(), nullable=False),
    sa.Column('is_24_7', sa.Boolean(), nullable=False),
    sa.Column('is_toll_free', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_hotlines_governorate_id'), 'emergency_hotlines', ['governorate_id'], unique=False)
    op.create_index(op.f('ix_emergency_hotlines_hotline_type'), 'emergency_hotlines', ['hotline_type'], unique=False)
    op.create_index(op.f('ix_emergency_hotlines_name'), 'emergency_hotlines', ['name'], unique=False)
    op.create_index(op.f('ix_emergency_hotlines_number'), 'emergency_hotlines', ['number'], unique=False)
    op.create_index(op.f('ix_emergency_hotlines_sector_id'), 'emergency_hotlines', ['sector_id'], unique=False)
    op.create_table('government_offices',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('office_type', sa.Enum('CIVIL_REGISTRY', 'TRAFFIC', 'PASSPORT', 'REAL_ESTATE', 'TAX', 'COURT', 'NOTARY', 'MUNICIPALITY', 'POST_OFFICE', 'HEALTH', 'EDUCATION', 'POLICE', 'OTHER', name='office_type', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('governorate_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_alt', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('is_24_7', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['government_entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['governorate_id'], ['governorates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_offices_entity_id'), 'government_offices', ['entity_id'], unique=False)
    op.create_index(op.f('ix_government_offices_governorate_id'), 'government_offices', ['governorate_id'], unique=False)
    op.create_index(op.f('ix_government_offices_name'), 'government_offices', ['name'], unique=False)
    op.create_index(op.f('ix_government_offices_office_type'), 'government_offices', ['office_type'], unique=False)
    op.create_index(op.f('ix_government_offices_slug'), 'government_offices', ['slug'], unique=True)
    op.create_table('office_services',
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['government_offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('office_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('office_services')
    op.drop_index(op.f('ix_government_offices_slug'), table_name='government_offices')
    op.drop_index(op.f('ix_government_offices_office_type'), table_name='government_offices')
    op.drop_index(op.f('ix_government_offices_name'), table_name='government_offices')
    op.drop_index(op.f('ix_government_offices_governorate_id'), table_name='government_offices')
    op.drop_index(op.f('ix_government_offices_entity_id'), table_name='government_offices')
    op.drop_table('government_offices')
    op.drop_index(op.f('ix_emergency_hotlines_sector_id'), table_name='emergency_hotlines')
    op.drop_index(op.f('ix_emergency_hotlines_number'), table_name='emergency_hotlines')
    op.drop_index(op.f('ix_emergency_hotlines_name'), table_name='emergency_hotlines')
    op.drop_index(op.f('ix_emergency_hotlines_hotline_type'), table_name='emergency_hotlines')
    op.drop_index(op.f('ix_emergency_hotlines_governorate_id'), table_name='emergency_hotlines')
    op.drop_table('emergency_hotlines')
    # ### end Alembic commands ###
